// Generated by CoffeeScript 1.3.3
(function() {
  var fibonacci;

  fibonacci = function(x) {
    if (x === 0) {
      return 0;
    }
    if (x === 1) {
      return 1;
    }
    return fibonacci(x - 1) + fibonacci(x - 2);
  };

  exports.fibonacci = fibonacci;

}).call(this);
